final Map<String, String> arTranslation = {
  "leasingself": "التأجير\nالذاتي ",
  "leasingsmart": "التأجير\nالذكي",
  "logintoyouraccount": "تسجيل الدخول إلى حسابك",
  "identificationnumber": "رقم الهوية",
  "emailAddress": "عنوان البريد الالكترونى",
  "password": "كلمة المرور",
  "didyouforgetyourpassword": "هل نسيت كلمة المرور ؟  ",
  "login": "تسجيل دخول ",
  "continueasaguest": "الاستمرار كضيف",
  "loginwithyoursocialmediaaccount": "تسجيل الدخول بحساب التواصل الاجتماعي",
  "idonthaveanyaccountcreatenew": "ليس لدي أي حساب إنشاء جديد",
  "carpreview": "معاينة السيارة",
  "frontpictureofthecar": "صورة السيارة من الامام",
  "carpicturefromtheback": "صورة السيارة من الخلف",
  "pictureofthecarfromtheright": "صورة السيارة من اليمين",
  "pictureofthecarfromtheleft": "صورة السيارة من اليسار",
  "nextone": "التالي",
  "mycontract": "عقودي",
  "bookingrentalconfirmed": "تم تأكيد الحجز / التأجير",
  "preview": "معاينة",
  "more": "المزيد",
  "myreservations": "حجوزاتي",
  "arithmetic": "حسابي",
  "chooseyourcarnow": "اختر سيارتك الأن",
  "pickupanddropofflocation": "موقع الاستلام والتسليم",
  "deliverytoanotherlocation": "التسليم إلي موقع آخر ",
  "receiveddate": "تاريخ الاستلام",
  "deliverydate": "تاريخ التسليم",
  "alreadyhaveareservation": "لديك حجز بالفعل ؟",
  "offers": "عروض",
  "day": "يوم",
  "hyundai": "هيونداي",
  "sonata": "سوناتا",
  "reservation": "حجز",
  "bmw": "بي أم دبليو",
  "receivinglocation": "موقع الاستلام ",
  "deliverylocation": "موقع التسليم",
  "findabranch": "البحث عن فرع",
  "branchlocation": "موقع الفرع",
  "city": "المدينه",
  "workdays": "أيام العمل",
  "fromsaturdaytothursdayfromamtopm": "من السبت الي الخميس  من 7ص : 10 م",
  "mobilenumber": "رقم الجوال",
  "search": "ابحث",
  "fleet": "الأسطول",
  "branches": "الفروع",
  "queries": "استفسارات",
  "abouttravel": "حول ترفل",
  "connectwithus": "تواصل معنا",
  "settings": "الإعدادات",
  "cooperationcouncilvisitor": "مجلس تعاون/زائر",
  "saudiresident": "سعودي / مقيم",
  "dateofbirth": "تاريخ الميلاد",
  "email": "البريد الالكتروني",
  "theaddress": "العنوان",
  "emphasis": "تأكيد",
  "skip": "تخطي",
  "all": "الكل",
  "active": "نشط",
  "therearenodata": "لا يوجد بيانات",
  "reservationmanagement": "إدارة الحجز",
  "reservationnumber": "رقم الحجز",
  "followuponbooking": "متابعة الحجز",
  "changepassword": "تغيير كلمة المرور",
  "entertheoldpassword": "أدخل كلمة المرور القديمة",
  "enterthenewpassword": "أدخل كلمة المرور الجديدة",
  "save": "حفظ",
  "underclaim": "تحت المطالبة",
  "closed": "مغلق",
  "receiptanddeliverydatetime": "تاريخ الاستلام والتسليم /التوقيت",
  "expertevaluation": "تقييم الخبراء",
  "ratingratingonascalefrom": "تصنيف التصنيف على مقياس من 1 إلى 5",
  "consumption": "الاستهلاك",
  "comfort": "راحة",
  "safety": "سلامة",
  "cancellationofreservation": "إلغاء الحجز",
  "reservationconfirmation": "تأكيد الحجز",
  "properties": "خصائص",
  "leasing": "تأجير",
  "whatisyourchoice": "ماهو خيـــارك؟ر ",
  "economic": "اقتصادي",
  "sortbylowestprice": "الفرز حسب الأقل سعراً",
  "details": "تفاصيل",
  "sort": "فرز",
  "category": "الفئة",
  "type": "النوع",
  "continuation": "استمرار",
  "goldmembership": "العضوية الذهبية",
  "silvermembership": "العضوية الفضية",
  "platinummembership": "العضوية البلاتينية",
  "advantages": "المزايا",
  "freedaily": "15.0كم مجاني يومياً.",
  "discountonthetotalrentalvalue": "% خصم علي إجمالي قيمة الإيجار.",
  "thecost": "التكلفة",
  "contracts": "الالعقود",
  "riyals": "ريال",
  "youhavenomembers": "لا يوجد لديك أعضاء",
  "learnmoreaboutamyali": "أعرف المزيد عن أميالي",
  "organic": "العضوية",
  "amyli": "أميالي",
  "myfriends": "أصدقائي",
  "notices": "اشعارات",
  "familymembership": "عضوية العائلة",
  "notifications": "اشعارات",
  "categories": "فئات",
  "i": "أنا",
  "enterusername": "ادخل اسم المستخدم",
  "enterpassword": "أدخل كلمة المرور",
  "pleaseentervalidpassword": "الرجاء إدخال كلمة مرور صالحة",
  "enterconfirmpassword": "أدخل تأكيد كلمة المرور",
  "passwrddoesnotmatch": "كلمة المرور غير متطابقة",
  "enterreservationnumber": "أدخل رقم الحجز",
  "languages": "اللغات",
  "selectyourpreferredlanguage": "اختر لغتك المفضلة",
  "confirmlanguage": "تأكيد اللغة",
  "logout": "تسجيل خروج",
  "cancel": "يلغي",
  "name": "اسم",
  "message": "رسالة",
  "submit": "يُقدِّم",
  "areyoulogout": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "enterEmailAddress": "الرجاء إدخال عنوان البريد الإلكتروني",
  "createyouraccount": "أنشئ حسابك",
  "register": "تسجيل",
  "nointernetconnection": "لا يوجد اتصال بالإنترنت!",
  "somethingwentwrong": "هناك خطأ ما",
  "servernotfound": "500 خادم غير موجود!",
  "passwordchangesuccessfully": "تم تغيير كلمة المرور بنجاح",
  "pleaseenterconfirmpassword": "الرجاء إدخال تأكيد كلمة المرور",
  "passworddoesnotmatch": "كلمة المرور غير متطابقة",
  "passwordresetsuccess": "إعادة تعيين كلمة المرور بنجاح",
  "createpassword": "أنشئ كلمة مرور",
  "newpassword": "كلمة السر الجديدة",
  "entervalidemailaddresss": "يرجى إدخال عنوان بريد إلكتروني صالح",
  "entervalidotp": "الرجاء إدخال otp صالح",
  "entermailtoreceivecode":
      "يرجى إدخال عنوان بريدك الإلكتروني لتلقي رمز التحقق",
  "enterotp": "أدخل OTP",
  "backtologin": "العودة إلى تسجيل الدخول",
  "firstnamerequired": "مطلوب حقل الاسم الأول.",
  "lastnamerequired": "حقل الاسم الأخير مطلوب.",
  "pleaseentervalidphoneno": "يرجى إدخال رقم هاتف صالح",
  "selectfirstbranch": "يرجى أولا تحديد الفرع الخاص بك",
  "firstname": "الاسم الاول",
  "lastname": "اللقب",
  "phoneNo": "رقم الهاتف",
  "selectyourbranch": "حدد الفرع الخاص بك",
  "alreadyhaveanaccount": "هل لديك حساب؟ تسجيل الدخول",
  "appupdateavailable": "تحديث التطبيق متاح",
  "next": "التالي",
  "update": "تحديث",
  "verifyEmail": "التحقق من البريد الإلكتروني",
  "verify": "يؤكد",
  "pleaseentervalidfirstname": "الرجاء إدخال الاسم الأول صالح",
  "pleaseentervalidlastname": "الرجاء إدخال اسم عائلة صالح",
  "pleaseentervalidaddress": "الرجاء إدخال عنوان صالح",
  "editProfile": "تعديل الملف الشخصي",
  "address": "تبوك",
  "bookingDetails": "تفاصيل الحجز",
  "bookingid": "معرف الحجز",
  "pickuplocation": "اختر موقعا",
  "cardetails": "تفاصيل السيارة",
  "companyname": "اسم الشركة",
  "carmodel": "طراز السيارة",
  "sit": "يجلس",
  "km": "كم",
  "branchdetails": "تفاصيل الفرع",
  "branchname": "اسم الفرع",
  "contactnumber": "رقم الاتصال",
  "driverdetails": "تفاصيل السائق",
  "fullname": "الاسم الكامل",
  "carbookwithdriver": "كتاب السيارة مع السائق",
  "confirmBooking": "حجز",
  "pleaseenterdeliverylocation": "الرجاء إدخال موقع التسليم",
  "carreservation": "حجز السيارة فقط",
  "pleaseenterreceivinglocation": "الرجاء إدخال موقع الاستلام",
  "selectReceiveDate": "حدد تاريخ الاستلام",
  "selectDeliveryDate": "حدد تاريخ التسليم",
  "bookingsuccessfully": "تم الحجز بنجاح",
  "bookCar": "حجز السيارة",
  "nothinghereyet": "لا شيء هنا بعد ...",
  "openClose": "فتح - إغلاق",
  "sunday": "الأحد",
  "monday": "الاثنين",
  "tuesday": "يوم الثلاثاء",
  "wednesday": "الأربعاء",
  "thursday": "يوم الخميس",
  "friday": "جمعة",
  "saturday": "السبت",
  "enteremail": "أدخل البريد الإلكتروني",
  "entername": "أدخل الاسم",
  "entermessage": "أدخل رسالة",
  "yourmessagesentsuccessfully": "تم إرسال رسالتك بنجاح",
  "aboutus": "معلومات عنا",
  "companyinformation": "معلومات الشركة",
  "contactinformation": "معلومات التواصل",
  "companyAddress": "عنوان الشركة",
  "toconfirmthisorder": "لتأكيد هذا الطلب ،",
  "pleasecontactthisbranch": "الرجاء الاتصال بهذا الفرع",
  "cancelbooking": "إلغاء الحجز",
  "mybookings": "حجوزاتي",
  "personalDetails": "تفاصيل شخصية",
  "send": "إرسال",
  "myprofile": "ملفي",
  "membership": "العضوية",
  "silvermembership": "العضوية الفضية",
  "goldenmembership": "العضوية الذهبية",
  "platinummembership": "العضوية البلاتينية",
  "contracts": "العقود",
  "costs": "التكلفة",
  "rayal": " ريال",
  "donnothavemember": "لا يوجد لديك أعضاء",
  "learnmoreaboutmiles": "أعرف المزيد عن أميالي",
  "advantages": "المزايا",
  "free8km": "8.0كم مجاني يومياً",
  "free150km": "15.0كم مجاني يومياً",
  "free30km": "30.0كم مجاني يومياً",
  "getmembership": "احصل على العضوية",
  "discountontotalrentalvalue": "% خصم علي إجمالي قيمة الإيجار",
  "gettheroute": "احصل على الطريق",
  "entervalidfullname": "أدخل اسمًا كاملاً صالحًا",
  "entervalididentificationnumber": "الرجاء رقم التعريف الصحيح",
  "selectvaliddob": "حدد تاريخ ميلاد صالح",
  "chosepaymentmethod": "اختر طريقة الدفع",
  "clickoneofoption": "انقر فوق أحد الخيارات أدناه",
  "cardnumber": "رقم البطاقة",
  "holdername": "اسم الحامل",
  "expirymonth": "شهر انتهاء الصلاحية",
  "expiryyear": "سنة انتهاء الصلاحية",
  "pay": "يدفع",
  "cvv": "CVV",
  "fillmissingfields": "الرجاء ملء الحقول الناقصة",
  "categories": "فئات",
};
