final enTranslation = {
  "leasingself": "Leasing\nSelf",
  "leasingsmart": "Leasing\nSmart",
  "logintoyouraccount": "Log in to your account",
  "identificationnumber": "Identification Number",
  "emailAddress": "Email address",
  "password": "Password",
  "didyouforgetyourpassword": "Did you forget your password ?",
  "login": "Login",
  "continueasaguest": "Continue as a guest",
  "loginwithyoursocialmediaaccount": "Log in with your social media account",
  "idonthaveanyaccountcreatenew": "I don't have any account Create new",
  "carpreview": "Car preview",
  "frontpictureofthecar": "Front picture of the car",
  "carpicturefromtheback": "Car picture from the back",
  "pictureofthecarfromtheright": "Picture of the car from the right",
  "pictureofthecarfromtheleft": "Picture of the car from the left",
  "nextone": "Next one",
  "mycontract": "Contracts",
  "bookingrentalconfirmed": "Booking / rental confirmed",
  "preview": "Preview",
  "more": "More",
  "myreservations": "Bookings",
  "arithmetic": "Profile",
  "chooseyourcarnow": "Choose your car now",
  "pickupanddropofflocation": "Pick-up and drop-off location",
  "deliverytoanotherlocation": "Delivery to another location",
  "receiveddate": "Received date",
  "deliverydate": "Delivery date",
  "alreadyhaveareservation": "Already have a reservation?",
  "offers": "Offers",
  "categories": "Categories",
  "hyundai": "Hyundai",
  "sonata": "Sonata",
  "reservation": "Reservation",
  "bmw": "BMW",
  "receivinglocation": "Receiving location",
  "deliverylocation": "Delivery location",
  "findabranch": "Find a branch",
  "branchlocation": "Branch location",
  "city": "City",
  "workdays": "Workdays",
  "fromsaturdaytothursdayfromamtopm":
      "From Saturday to Thursday from 7 am to 10 pm",
  "mobilenumber": "Mobile number",
  "search": "Search",
  "fleet": "Fleet",
  "branches": "Branches",
  "queries": "Queries",
  "abouttravel": "About Travel",
  "connectwithus": "Connect with us",
  "settings": "Settings",
  "cooperationcouncilvisitor": "Cooperation Council/Visitor",
  "saudiresident": "Saudi / resident",
  "dateofbirth": "Date of Birth",
  "email": " E-mail",
  "theaddress": "The address",
  "emphasis": "Emphasis",
  "skip": "Skip",
  "all": "All",
  "active": "Active",
  "therearenodata": "There are no data",
  "reservationmanagement": "Reservation management",
  "reservationnumber": "Reservation number",
  "followuponbooking": "Follow up on booking",
  "changepassword": "Change password",
  "entertheoldpassword": "Enter the old password",
  "enterthenewpassword": "Enter the new password",
  "save": "Save",
  "underclaim": "Under claim",
  "closed": "Closed",
  "receiptanddeliverydatetime": "Receipt and delivery date/time",
  "expertevaluation": "Expert evaluation",
  "ratingratingonascalefrom": "Rating rating on a scale from 1 to 5",
  "consumption": "Consumption",
  "comfort": "Comfort",
  "safety": "Safety",
  "cancellationofreservation": "Cancel",
  "reservationconfirmation": "Confirm",
  "properties": "Properties",
  "leasing": "Leasing",
  "whatisyourchoice": "What is your choice?",
  "economic": "Economic",
  "sortbylowestprice": "Sort by lowest price",
  "day": "Day",
  "sort": "Sort",
  "category": "Category",
  "type": "Type",
  "continuation": "Continuation",
  "goldmembership": "Gold Membership",
  "silvermembership": "Silver Membership",
  "platinummembership": "Platinum Membership",
  "advantages": "Advantages",
  "freedaily": "15.0 km free daily.",
  "discountonthetotalrentalvalue": "% Discount on the total rental value.",
  "thecost": "The cost",
  "contracts": "Contracts",
  "riyals": "riyals",
  "youhavenomembers": "You have no members",
  "learnmoreaboutamyali": "Learn more about Amyali",
  "organic": "Organic",
  "amyli": "AMYLI",
  "myfriends": "My friends",
  "notices": "Notices",
  "familymembership": "Family Membership",
  "notifications": "Notifications",
  "categories": "Categories",
  "i": "I",
  "enterusername": "Enter User Name",
  "enterpassword": "Enter password",
  "pleaseentervalidpassword": "Please enter valid password",
  "enterconfirmpassword": "Enter Confirm Password",
  "passwrddoesnotmatch": "Password does not match",
  "enterreservationnumber": "Enter Reservation Number",
  "languages": "Languages",
  "selectyourpreferredlanguage": "Select your preferred language",
  "confirmlanguage": "Confirm Language",
  "logout": "Log out",
  "cancel": "Cancel",
  "name": "Name",
  "message": "Message",
  "submit": "Submit",
  "areyoulogout": "Are you sure you want to log out?",
  "enterEmailAddress": "Please enter email address",
  "createyouraccount": "Create your account",
  "register": "Register",
  "nointernetconnection": "No Internet Connection!",
  "somethingwentwrong": "Something went wrong",
  "servernotfound": "500 Server not found!",
  "passwordchangesuccessfully": "Password change successfully",
  "pleaseenterconfirmpassword": "Please enter confirm password",
  "passworddoesnotmatch": "Password doesn't match",
  "passwordresetsuccess": "Password reset successfully",
  "createpassword": "Create Password",
  "newpassword": "New Password",
  "entervalidemailaddresss": "Please enter a valid email address",
  "entervalidotp": "Please enter valid otp",
  "entermailtoreceivecode":
      "Please enter your email address to receive a verification code",
  "checkmailwehavesentotp":
      "Please check your email - we have sent OTP message",
  "enterotp": "Enter OTP",
  "backtologin": "Back to Login",
  "firstnamerequired": "The first name field is required.",
  "lastnamerequired": "The last name field is required.",
  "pleaseentervalidphoneno": "Please enter a valid Phone number",
  "selectfirstbranch": "Please first select your branch",
  "firstname": "First name",
  "lastname": "Last name",
  "phoneNo": "Phone number",
  "selectyourbranch": "Select your branch",
  "alreadyhaveanaccount": "Already have an account? Login",
  "appupdateavailable": "App Update Available",
  "next": "Next",
  "update": "Update",
  "verifyEmail": "Verify Email",
  "verify": "Verify",
  "pleaseentervalidfirstname": "Please enter valid first name",
  "pleaseentervalidlastname": "Please enter valid last name",
  "pleaseentervalidaddress": "Please enter valid address",
  "editProfile": "Edit Profile",
  "address": "Address",
  "bookingDetails": "Booking Details",
  "bookingid": "Booking ID",
  "pickuplocation": "Pickup Location",
  "cardetails": "Car Details",
  "companyname": "Company Name",
  "carmodel": "Car model",
  "sit": "Sit",
  "km": "km",
  "branchDetails": "Branch Details",
  "branchname": "Branch Name",
  "contactnumber": "Contact Number",
  "driverdetails": "Driver's Details",
  "fullname": "Full Name",
  "carbookwithdriver": "Car book with driver",
  "confirmBooking": "Confirm Booking",
  "pleaseenterdeliverylocation": "Please enter delivery location",
  "pleaseenterreceivinglocation": "Please enter receiving location",
  "selectReceiveDate": "Select receive date",
  "selectDeliveryDate": "Select delivery date",
  "bookingsuccessfully": "Booking Successfully",
  "bookCar": "Book Car",
  "nothinghereyet": "Nothing here yet...",
  "openClose": "Open - Close",
  "sunday": "Sunday",
  "monday": "Monday",
  "tuesday": "Tuesday",
  "wednesday": "Wednesday",
  "thursday": "Thursday",
  "friday": "Friday",
  "saturday": "Saturday",
  "enteremail": "Enter Email",
  "entername": "Enter Name",
  "entermessage": "Enter Message",
  "yourmessagesentsuccessfully": "Your message sent successfully",
  "aboutus": "About Us",
  "companyinformation": "Company Information",
  "contactinformation": "Contact Information",
  "companyAddress": "Company Address",
  "toconfirmthisorder": "To confirm this order,",
  "pleasecontactthisbranch": "Please contact this branch",
  "cancelbooking": "Cancel Booking",
  "mybookings": "My Bookings",
  "personalDetails": "Personal Details",
  "send": "Send",
  "details": "Details",
  "membership": "Membership",
  "silvermembership": "Silver Membership",
  "goldenmembership": "Gold Membership",
  "platinummembership": "Platinum Membership",
  "contracts": "Contracts",
  "costs": "Cost",
  "rayal": "SAR",
  "donnothavemember": "Don't Have Member",
  "learnmoreaboutmiles": "Learn more about my miles",
  "advantages": "Advantages",
  "myprofile": "My profile",
  "free150km": "15.0 km free daily",
  "free8km": "8.0 km free daily",
  "free30km": "30.0 km free daily",
  "getmembership": "Get Membership",
  "chosepaymentmethod": "Choose a Payment Method",
  "clickoneofoption": "Click one of the option below",
  "discountontotalrentalvalue": "% discount on the total rental value",
  "gettheroute": "Get the route",
  "entervalidfullname": "Enter valid full name",
  "entervalididentificationnumber": "Please valid Identification number",
  "selectvaliddob": "Select valid date of birth",
  "cardnumber": "Card Number",
  "holdername": "Holder Name",
  "expirymonth": "Expiry Month",
  "expiryyear": "Expiry Year",
  "pay": "Pay",
  "cvv": "CVV",
  "fillmissingfields": "Please fill missing fields"
};
