name: traval
description: A new Flutter project.
publish_to: "none"
version: 1.0.16+27

environment:
  sdk: ">=2.17.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  carousel_slider: ^4.1.1
  # hyperpay: ^1.0.0-dev.2
  connectivity_plus: ^2.3.0
  change_app_package_name: ^1.1.0
  device_info_plus: ^4.1.2
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  firebase_auth: ^3.8.0
  flutter_calendar_carousel: ^2.1.0
  firebase_core: ^1.21.1
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^4.4.1
  firebase_messaging: ^13.0.0
  flutter_rating_bar: ^4.0.1
  flutter_secure_storage: ^6.0.0
  flutter_svg: ^1.1.0
  flutter_switch: ^0.3.2
  get: ^4.6.1
  get_storage: ^2.0.3
  google_maps_flutter: ^2.1.5
  google_sign_in: ^5.4.1
  http: ^0.13.4
  intl: ^0.17.0
  image_cropper: ^3.0.0
  image_picker: ^0.8.5+3
  location: ^4.4.0
  month_picker_dialog: ^0.4.0
  path: ^1.8.1
  package_info_plus: ^1.0.6
  sign_in_with_apple: ^4.1.0
  smooth_page_indicator: ^1.0.0+2
  timeline_tile: ^2.0.0
  url_launcher: ^6.1.2
  flutter_local_notifications: ^12.0.3
  jiffy: ^5.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
  fonts:
    - family: Popins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
